### ISSUE TITLE
ループでカスタムノーツの位置が狂う

### ISSUE THREAD

**Issue by ghost** [denpadokei/PracticePlugin#20]
v1.21で、カストムノーツを使うと曲がループした時にノーツの位置が狂ってしまいます。デフォルトノーツなら問題はありません。

https://youtu.be/5XaRe_DyuJc

必要なコアモッドとカスタムノーツとCamera2しかインストールされていないプレイ環境でも同じでした。

**Comment by denpadokei** [comment]
報告ありがとうございます。
修正しました。
