### ISSUE TITLE
シークバーの再生位置ではなく曲の始点からスタートする

### ISSUE THREAD

**Issue by ghost** [denpadokei/PracticePlugin#21]
一旦メニューに出てまた同じ曲の練習に入ったところでシークバーの再生位置とループの始点と終点などが記憶されていますがシークバーをまたいじらないとコンティニューする時にシークバーが示すところではなく曲の始点からスタートします。

https://youtu.be/5XaRe_DyuJc

必要なコアモッドとカスタムノーツとCamera2しかインストールされていないプレイ環境でも同じでした。

**Comment by denpadokei** [comment]
報告ありがとうございます。
修正しました。
